name: article-streaming
on:
  pull_request:
    branches:
      - main
jobs:
  run-tests:
    name: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
            python-version: '3.13'
      - name: requirements
        run: pip install -r requirements.txt
      - name: Run checks
        run: pytest